title: das Neves - Blog!
description: > # this means to ignore newlines until "baseurl:"
  Experiências, projetos, dicas, tecnologia, viagens e tudo o que faço e vejo de produtivo
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gabriel das Neves # add your name
author-img: eu.jpg # add your photo
about-author: Um entusiasta da Ciência, amante da Engenharia, mochileiro, louco por Surf, músico amador e apreciador de causas sociais. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: gabrieldasneves # add your Github handle
social-linkedin: https://www.linkedin.com/in/gabriel-das-neves/
social-email: galvesdasneves@gmail.com # add your Email address

# Disqus
discus-identifier: das neves # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
